### ISSUE TITLE
Use `.bind()` instead of arrow functions

### ISSUE THREAD

**Issue by mlodato517** [shogogg/ts-deferred#2]
To allow mocking `Deferred.prototype.resolve`/`Deferred.prototype.reject` in `jest`, we could bind `this` via
```
this.resolve = this.resolve.bind(this)
this.reject = this.reject.bind(this)
```
and make `resolve` and `reject` regular functions instead of arrow functions.

**Comment by shogogg** [comment]
@mlodato517 Hi, thanks to your suggestion.

But it's hard for me to implement. Please see #1.

When `resolve` and `reject` are regular function, they cannot bound to the Deferred instance.

Modified code:
```
export class Deferred<T> {

  private readonly _promise: Promise<T>
  private _resolve: (value?: T | PromiseLike<T>) => void
  private _reject: (reason?: any) => void

  constructor () {
    this._promise = new Promise<T>((resolve, reject) => {
      this._resolve = resolve.bind(this)
      this._reject = reject.bind(this)
    })
  }

  get promise (): Promise<T> {
    return this._promise
  }

  resolve (value?: T | PromiseLike<T>): void  {
    return this._resolve(value)
  }

  reject (reason?: any): void {
    return this._reject(reason)
  }

}
```

Run:
```
const deferred = new Deferred<any>()
const resolve = deferred.resolve
resolve('result')
// TypeError: Cannot read property '_resolve' of undefined
```

1. Why are you mocking prototype object instead of instance?
2. Do you have any ideas?

**Comment by mlodato517** [comment]
@shogogg Thanks for taking a look at this!

I think the prototype functions should be bound. I had tried this locally and it _appeared_ to work, but I'm no JS expert
```
export class Deferred<T> {

  private readonly _promise: Promise<T>
  private _resolve: (value?: T | PromiseLike<T>) => void
  private _reject: (reason?: any) => void

  constructor () {
    this._promise = new Promise<T>((resolve, reject) => {
      this._resolve = resolve
      this._reject = reject
    })
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  get promise (): Promise<T> {
    return this._promise
  }

  resolve (value?: T | PromiseLike<T>): void  {
    return this._resolve(value)
  }

  reject (reason?: any): void {
    return this._reject(reason)
  }

}
```

> Why are you mocking prototype object instead of instance?

I'm just mocking the prototype because the deferred instance lives on another object and it's private and I don't think it should be public (although that could have been shit design, I honestly don't know what I'm doing)

**Comment by shogogg** [comment]
@mlodato517 It seems like don't work you expected.

### Example:
```typescript
// PASS
it('pass', () => {
  // Setup
  const deferred = new Deferred<any>()
  const spy = jest.spyOn(Deferred.prototype, 'resolve')

  // Run
  deferred.resolve('result')

  // Assert
  expect(spy).toBeCalled()

  // Cleanup
  jest.restoreAllMocks()
})

// FAIL
it('fails', () => {
  // Setup
  const deferred = new Deferred<any>()
  deferred.resolve = deferred.resolve.bind(deferred) // Add this line
  const spy = jest.spyOn(Deferred.prototype, 'resolve')

  // Run
  deferred.resolve('result')

  // Assert
  expect(spy).toBeCalled()
  // This test will fail, because `deferred.resolve()` doesn't call prototype function.

  // Cleanup
  jest.restoreAllMocks()
})
```

> I'm just mocking the prototype because the deferred instance lives on another object and it's private and I don't think it should be public (although that could have been shit design, I honestly don't know what I'm doing)

I think you can use [ES6 Class Mocks](https://jestjs.io/docs/en/es6-class-mocks) instead of mocking prototype.

**Comment by mlodato517** [comment]
@shogogg If I copy those tests locally and then move the `jest.spyOn` lines to before the `Deferred` is constructed, they both pass. Could that be the reason?

The reason I wanted to move away from arrow functions was because of that part of the article you linked that says:

>Please note that if you use arrow functions in your classes, they will not be part of the mock. The reason for that is that arrow functions are not present on the object's prototype, they are merely properties holding a reference to a function.

Before I reported this issue, to get around the problem for us, I copied this project's `index.ts` into our project and changed the arrow functions to use `.bind` instead. I'm able to mock the prototype and all our tests pass. I just feel bad having copied your code into my project instead of using your project.

**Comment by mlodato517** [comment]
@shogogg I see you added https://github.com/shogogg/ts-deferred/commit/de88bd6bf2b3d3da0a6aa62587b366d318c3b70e which is awesome 👍 
Unfortunately, it doesn't address the situation I was talking about (when you don't have access to the `deferred` object because it's privately contained in the class you're testing) so I made #3 if you wanted to take a look but I'm totally fine with leaving them as arrow functions if the `.bind(this)` solution is undesirable (and if it is, I'd love to hear why because I don't really know what other benefits of arrow functions there might be!)

**Comment by mlodato517** [comment]
I think this is sufficiently stale to close :-)
